name: mb_rmuti_profile_demo
description: "APP RMUTI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # ปรับตรงนี้เพื่อให้รองรับ Library ใหม่ๆ

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  barcode: ^2.2.9
  barcode_widget: ^2.0.4
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.4
  flutter_riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/item/
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/kaint/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/kaint/Kanit-Bold.ttf
          weight: 700